### ISSUE TITLE
Flash is broken

### ISSUE THREAD

**Issue by CaptainChicky** [CaptainChicky/Trojan.JS.Youareanidiot#2]
Please make html5 version or supply non-broken plugin installation or soemthing

**Comment by SonicFan2020-best** [comment]
just try using ruffle or something

[Ruffle](htttps://ruffle.rs)

**Comment by SonicFan2020-best** [comment]
![img1](https://user-images.githubusercontent.com/59418653/143472312-b4c3612b-4ba0-4a8b-8a69-2be435fe95da.jpg)

**Comment by SonicFan2020-best** [comment]
then try more

**Comment by CaptainChicky** [comment]
I've converted the trojan to html5, but this is beyond the scope of the repository, since it is an archival one and seeks to keep it close to the original as possible. 

If you want to see the recreation, or even just a more comprehensive overview, please visit [this writeup](https://theaviary.me/Idiot!/). Thanks!
